spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wikimedia-recent-changes?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    use-sql-comments: true
    format-sql: true
    hibernate:
      ddl-auto: create-drop
